### PR TITLE
General code cleanup + minor speed upgrade

### PR DESCRIPTION
**Pull request by RandomAnonymousPerson**

### CODE REVIEW

**Comment by RandomAnonymousPerson** [comment]
File conversions are only partially moved, i will do them i steps.
This should be stable version where i tested what i changed.
I will move the conversions of other file types to separate classes following same logic in future updates, which might come a bit later though as they will require more testing ect., which is why i posted the pull request now.

**Comment by RandomAnonymousPerson** [comment]
There were few general changes made across files:
1. general code cleanup like before
2. removing regions, which will be removed across all files later. regions are ide specific not language specific and they seem to be the cause of bloated classes like utilities ect. which now have to be cleaned up. in case of small neat classes that do specific thing, regions just unnecessarily enlarge the code and worsen readability.
3. fixed namespaces, which now should be unified across classes
4. moving file conversions to separate classes, each handling specific part of file/file type
5. updating the file conversions to be simpler and faster

**Comment by RandomAnonymousPerson** [comment]
Class ImageConverter is temporary, i have to inspect file conversions further to move the current content to a more sensible class.
I will be looking at tiles next, after that i should finish the cleanup and remove this class, as atm. im not yet sure how all the existing code will be related.

**Comment by PodeCaradox** [comment]
thanks for helping out, yeah clean code was at the time i wrote that not learned by me x)
Do you want rights for the projects so you can add ther request by yourself?

**Pull request merged**
